### ISSUE TITLE
Coordinate Reference Systems to support?

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/WEBPROJ#1]
Which CRS's should be supported?

Below are preliminary lists for DK and GL:

### Denmark

System34 Jylland
System34 Sjælland
System45 Bornholm
KP2000 Jylland
KP2000 Jylland + DVR90 heights
KP2000 Jylland + DNN heights
KP2000 Sjælland
KP2000 Sjælland + DVR90 heights
KP2000 Sjælland + DNN heights
KP2000 Bornholm
KP2000 Bornholm + DVR90 heights
KP2000 Bornholm + DNN heights
DKTM1
DKTM1 + DVR90 heights
DKTM1 + DNN heights
DKTM2
DKTM2 + DVR90 heights
DKTM2 + DNN heights
DKTM3
DKTM3 + DVR90 heights
DKTM3 + DNN heights
DKTM4
DKTM4 + DVR90 heights
DKTM4 + DNN heights
ETRS89 / UTM Zone 32N
ETRS89 / UTM Zone 32N + DVR90 heights
ETRS89 / UTM Zone 32N + DNN heights
ETRS89 / UTM Zone 33N
ETRS89 / UTM Zone 33N + DVR90 heights
ETRS89 / UTM Zone 33N + DNN heights
DVR90
Dansk Normal Nul

### Greenland

GVR2000, Greenlandic Vertical Reference of 2000
GVR2016, Greenlandic Vertical Reference of 2016
GR96 / UTM Zone 18N
GR96 / UTM Zone 18N + GVR2000 heights
GR96 / UTM Zone 18N + GVR2016 heights
GR96 / UTM Zone 19N
GR96 / UTM Zone 19N + GVR2000 heights
GR96 / UTM Zone 19N + GVR2016 heights
GR96 / UTM Zone 20N
GR96 / UTM Zone 20N + GVR2000 heights
GR96 / UTM Zone 20N + GVR2016 heights
GR96 / UTM Zone 21N
GR96 / UTM Zone 21N + GVR2000 heights
GR96 / UTM Zone 21N + GVR2016 heights
GR96 / UTM Zone 22N
GR96 / UTM Zone 22N + GVR2000 heights
GR96 / UTM Zone 22N + GVR2016 heights
GR96 / UTM Zone 23N
GR96 / UTM Zone 23N + GVR2000 heights
GR96 / UTM Zone 23N + GVR2016 heights
GR96 / UTM Zone 24N
GR96 / UTM Zone 24N + GVR2000 heights
GR96 / UTM Zone 24N + GVR2016 heights
GR96 / UTM Zone 25N
GR96 / UTM Zone 25N + GVR2000 heights
GR96 / UTM Zone 25N + GVR2016 heights
GR96 / UTM Zone 26N
GR96 / UTM Zone 26N + GVR2000 heights
GR96 / UTM Zone 26N + GVR2016 heights
GR96 / UTM Zone 27N
GR96 / UTM Zone 27N + GVR2000 heights
GR96 / UTM Zone 27N + GVR2016 heights
GR96 / UTM Zone 28N
GR96 / UTM Zone 28N + GVR2000 heights
GR96 / UTM Zone 28N + GVR2016 heights
GR96 / UTM Zone 29N
GR96 / UTM Zone 29N + GVR2000 heights
GR96 / UTM Zone 29N + GVR2016 heights

### Faeroe Islands

Undecided as of now.

**Comment by larsnaesbye** [comment]
These are the ones currently needed for our geokeys service:

UTM32 & UTM33: EPSG:25832, EPSG:25833, EPSG:32632, EPSG:32633
DKTM: EPSG:4093, EPSG:4094, EPSG:4095, EPSG:4096
System34/45:  EPSG:34003 (Jylland), EPSG:34005(Sjælland), EPSG: 45001(Bornholm)
WGS84: EPSG:4326
World Mercator: EPSG:3395
Spherical Mercator: EPSG:3857

**Comment by kbevers** [comment]
> System34/45: EPSG:34003 (Jylland), EPSG:34005(Sjælland), EPSG: 45001(Bornholm)

Just FYI, these are invalid EPSG codes. System34/45 is not yet available in the EPSG register.

**Comment by larsnaesbye** [comment]
I know, but the geokeys service currently uses them anyway. I can fix this behind the scenes for backwards compatibility of course.

**Comment by kbevers** [comment]
> UTM32 & UTM33: EPSG:25832, EPSG:25833, EPSG:32632, EPSG:32633
DKTM: EPSG:4093, EPSG:4094, EPSG:4095, EPSG:4096
System34/45: EPSG:34003 (Jylland), EPSG:34005(Sjælland), EPSG: 45001(Bornholm)
WGS84: EPSG:4326
World Mercator: EPSG:3395
Spherical Mercator: EPSG:3857

Supported as of 39609172d5fe98e16ff8bea9d5558518e0eaa132
