### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by AskeFC** [Kortforsyningen/WEBPROJ#12]
It seems theres no or too restrictive CORS headers set. We are currently unable to implement webproj swaggerui in to docs.kortforsyningen.dk because of this.

**Comment by kbevers** [comment]
In my work CORS is "Continuously Operating Reference Station" which presumably is not what is meant here. Please enlighten me, or better yet, submit a pull request with a fix :-)

**Comment by AskeFC** [comment]
CORS in this context is "Cross-Origin Resource Sharing", see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS  for quite an elaborate and good explanation.
This issue does not directly concern the functionality of webproj, but rather the setup of the webserver currently hosting the swaggerui api.

**Comment by larsnaesbye** [comment]
It should be a matter of adding flask_cors and calling a function or two upon setup: https://flask-cors.readthedocs.io/en/latest/

I will concoct a fix and pull request soon.

**Comment by larsnaesbye** [comment]
Resolved by c23e5c94df45dda855d8fe7ee20e1441b2ad4aa3 and 9ef9dd992c8a00c5941e2abf71c25e58d182b05a .
