### ISSUE TITLE
Consider using flask-restplus in favour of flask-restful+flask-restful-swagger

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/WEBPROJ#5]
`flask-restplus` is a fork of `flask-restful` which includes support for Swagger, alleviating the need for the `flask-restful-swagger` package which isn't properly available via Conda (and generally not maintained it would seem).

Switching to `flask-restplus` is just a matter of changing the imports in `webproj\api.py` and removing the `flask-restful-swagger` import. Once the change is made the root entry-point display a nice documentation web page like this:

![swagger](https://user-images.githubusercontent.com/13132571/65182712-33125380-da62-11e9-8a61-9e4fb1ad4b04.PNG)

The documentation can be tweaked from the Python code. A quick guide to `flask-restplus` can be found here: https://towardsdatascience.com/working-with-apis-using-flask-flask-restplus-and-swagger-ui-7cf447deda7f

**Comment by larsnaesbye** [comment]
Nice. I did not know this.

**Comment by DocDemar** [comment]
sweet - mange tak

**Comment by kbevers** [comment]
@larsnaesbye Remember to update the Conda environment files too, otherwise Travis will fail

**Comment by larsnaesbye** [comment]
Oh, right. I don't use conda myself - I'll fix it.
